In [0]:
# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import numpy as np
import pandas as pd
import tensorflow.keras as keras
from google.colab import files
import os
from PIL import Image

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization

In [0]:
# Transforms test images to 227x227 and saves them to folder with ready signs

signs_test_root = "/content/drive/My Drive/DATA/SIGNS/test_signs/"
ready_signs_test_root = "/content/drive/My Drive/DATA/READY_SIGNS/test_signs/"
counter = 0
for filename in os.listdir(signs_test_root):
  image = Image.open(signs_test_root + filename)
  # summarize some details about the image
#   print(image.format)
#   print(image.mode)
#   print(image.size)
  # show the image
  image.thumbnail((227,227))
#   display(image)
  image.save(ready_signs_test_root + filename)
#   print(filename)
  counter += 1
  if (counter % 50 == 0):
    print('Saved ', counter, " photo")
print('Saved ', counter, ' photos')

Saved  50  photo
Saved  100  photo
Saved  120  photos


In [0]:
# signs_train_root = "/content/drive/My Drive/DATA/SIGNS/train_signs/"
# ready_signs_train_root = "/content/drive/My Drive/DATA/READY_SIGNS/train_signs/"
# counter = 0
# for filename in os.listdir(signs_train_root):
#   image = Image.open(signs_train_root + filename)
#   # summarize some details about the image
# #   print(image.format)
# #   print(image.mode)
# #   print(image.size)
#   # show the image
#   image.thumbnail((227,227))
# #   display(image)
#   image.save(ready_signs_train_root + filename)
#   print(filename)
#   counter += 1
#   print(counter)

In [0]:
# Creates dataframes for each type of sign

dataframes = []
for i in range(0,6):
  dataframe = pd.DataFrame(columns=['Name', "Location"])
  dataframes.append(dataframe)

In [0]:
# Loads signs from train_signs to dataframes

signs_train_root = "/content/drive/My Drive/DATA/SIGNS/train_signs/"
ready_signs_train_root = "/content/drive/My Drive/DATA/READY_SIGNS/train_signs/"
counter = 0
for filename in os.listdir(signs_train_root):
  index = int(filename[0])
  dataframes[index] = dataframes[index].append({
      'Name': filename,
      'Location': signs_train_root + filename
  }, ignore_index=True)

In [0]:
# Checks signs dataframe
dataframes[5].head()

Name                                           Location
0  5_IMG_5605.jpg  /content/drive/My Drive/DATA/SIGNS/train_signs...
1  5_IMG_5604.jpg  /content/drive/My Drive/DATA/SIGNS/train_signs...
2  5_IMG_5595.jpg  /content/drive/My Drive/DATA/SIGNS/train_signs...
3  5_IMG_5542.jpg  /content/drive/My Drive/DATA/SIGNS/train_signs...
4  5_IMG_5556.jpg  /content/drive/My Drive/DATA/SIGNS/train_signs...

In [0]:
# Transforms train_images to 227x227 and saves them to train/dev folder in 80/20 ratio

ready_signs_train_root = "/content/drive/My Drive/DATA/READY_SIGNS/train_signs/"
ready_signs_dev_root = "/content/drive/My Drive/DATA/READY_SIGNS/dev_signs/"
counter = 0
for frame in dataframes:
#   print('New Frame')
  for i in range(0, 180):
#     print(i)
    image_name = frame['Name'][i]
    image_location = frame['Location'][i]
    image = Image.open(image_location)
    image.thumbnail((227,227))
    if (i < 160):
      image.save(ready_signs_train_root + image_name)
    else:
      image.save(ready_signs_dev_root + image_name)
    counter += 1
    if (counter % 50 == 0):
      print("Saved ", counter, " photo")
  print('Saved ', counter, ' photos in a dataframe')

#   for i in range(160, 180):
    

Saved  50  photo
Saved  100  photo
Saved  150  photo
Saved  180  photos in a dataframe
Saved  200  photo
Saved  250  photo
Saved  300  photo
Saved  350  photo
Saved  360  photos in a dataframe
Saved  400  photo
Saved  450  photo
Saved  500  photo
Saved  540  photos in a dataframe
Saved  550  photo
Saved  600  photo
Saved  650  photo
Saved  700  photo
Saved  720  photos in a dataframe
Saved  750  photo
Saved  800  photo
Saved  850  photo
Saved  900  photo
Saved  900  photos in a dataframe
Saved  950  photo
Saved  1000  photo
Saved  1050  photo
Saved  1080  photos in a dataframe


In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
train_images = []
train_labels = []
scaler = StandardScaler()
number_of_features = 227 * 227 * 3

In [0]:
ready_signs_train_root = "/content/drive/My Drive/DATA/READY_SIGNS/train_signs/"

counter = 0
for filename in os.listdir(ready_signs_train_root):
  index = int(filename[0])
  label = np.zeros(6)
  label[index] = 1
  
  image = Image.open(ready_signs_train_root + filename)
  image_array = np.array(image)
  image_array = image_array.flatten()
#   if (counter == 0):
#     print(image_array)
  train_images.append(image_array)
  train_labels.append(label)
#   print(train_images[counter])
  counter += 1
  if (counter % 50 == 0):
    print(counter)

50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950


In [0]:
train_images = np.stack(train_images, axis = 0)
train_labels = np.stack(train_labels, axis = 0)

In [0]:
len(train_images)

960

In [0]:
train_images.shape

(960, 227, 227, 3)

In [0]:
train_images = scaler.fit_transform(train_images)

In [0]:
scaler.mean_

array([229.4875    , 221.48333333, 211.46145833, ..., 182.01145833,
       168.79791667, 158.32291667])

In [0]:
np.save('var', scaler.var_)

In [0]:
train_images[0]

array([3.10977058, 2.27879124, 1.9417691 , ..., 0.91520602, 0.73925699,
       0.68224949])

In [0]:
train_images[1]

array([ 0.62443945,  0.4979703 ,  0.23826476, ..., -1.96209773,
       -2.17979528, -2.20098606])

In [0]:
train_labels[1]

array([0., 0., 0., 0., 0., 1.])

In [0]:
dev_images = []
dev_labels = []

In [0]:
ready_signs_dev_root = "/content/drive/My Drive/DATA/READY_SIGNS/dev_signs/"

counter = 0
for filename in os.listdir(ready_signs_dev_root):
  index = int(filename[0])
  label = np.zeros(6)
  label[index] = 1
  
  image = Image.open(ready_signs_dev_root + filename)
  image_array = np.array(image)
  image_array = image_array.flatten()
  dev_images.append(image_array)
  dev_labels.append(label)
  
  counter += 1
  if (counter % 50 == 0):
    print(counter)

50
100


In [0]:
dev_images = np.stack(dev_images, axis = 0)
dev_labels = np.stack(dev_labels, axis = 0)
dev_images = scaler.transform(dev_images)

In [0]:
dev_images[0]

array([0.62443945, 1.09157728, 1.47717701, ..., 0.41821719, 0.40325097,
       0.36602365])

In [0]:
dev_images[1]

array([-0.86675923, -0.09563668,  0.54799282, ...,  0.65363295,
        0.80225811,  0.86826468])

In [0]:
dev_labels[1]

array([0., 0., 0., 0., 0., 1.])

In [0]:
print(train_images[0], '\n', train_labels[0])

[3.10977058 2.27879124 1.9417691  ... 0.91520602 0.73925699 0.68224949] 
 [1. 0. 0. 0. 0. 0.]


In [0]:
train_images_list = []
for image in train_images:
  train_images_list.append(np.reshape(image, (227, 227, 3)))

In [0]:
len(train_images_list)

960

In [0]:
train_images_list[0][0][150:170]

array([[-0.60620075, -0.98593693, -0.89435834],
       [-0.57990996, -0.9923977 , -0.88837909],
       [-0.5964512 , -1.0659403 , -0.93922591],
       [-0.64243133, -1.15266035, -1.01371764],
       [-0.69853685, -1.26882791, -1.10833989],
       [-0.90721216, -1.42765086, -1.26752373],
       [-0.82871665, -1.36062747, -1.22858774],
       [-1.03112595, -1.65035564, -1.45384477],
       [-1.18979334, -2.28527053, -1.86295032],
       [-1.17185262, -2.45972009, -2.01047764],
       [-0.89243593, -2.05485809, -1.78433163],
       [-0.88517997, -2.03033843, -1.77417023],
       [-0.89735128, -2.05989484, -1.78549403],
       [-1.12171045, -2.2534037 , -1.9408082 ],
       [-1.12060905, -2.25189174, -1.92486922],
       [-1.31831949, -2.42498744, -2.07089111],
       [-1.31239354, -2.41856324, -2.05864216],
       [-1.3146048 , -2.42115026, -2.07759566],
       [-1.45858537, -2.56357669, -2.19544911],
       [-1.45259981, -2.57219499, -2.20907341]])

In [0]:
print(dev_images[0], '\n', dev_labels[0])

[0.62443945 1.09157728 1.47717701 ... 0.41821719 0.40325097 0.36602365] 
 [1. 0. 0. 0. 0. 0.]


In [0]:
dev_images_list = []
for image in dev_images:
  dev_images_list.append(np.reshape(image, (227, 227, 3)))

In [0]:
dev_images_list[0][0][0:10]

array([[0.62443945, 1.09157728, 1.47717701],
       [0.62117448, 1.08867322, 1.47459293],
       [0.62113307, 1.0893985 , 1.47513466],
       [0.56257546, 1.04642305, 1.43432209],
       [0.56447407, 1.04878601, 1.43767856],
       [0.5031999 , 1.00515443, 1.39763433],
       [0.50379961, 1.00563475, 1.39894407],
       [0.50828283, 1.01068607, 1.4042029 ],
       [0.50900289, 1.01492098, 1.40441657],
       [0.5105193 , 1.01576531, 1.40567426]])

In [0]:
len(dev_images_list)

120

In [0]:
train_images = np.array(train_images_list)
train_labels = np.array(train_labels)
dev_images = np.array(dev_images_list)
dev_labels = np.array(dev_labels)

In [0]:
train_images.shape

(960, 227, 227, 3)

In [0]:
train_labels.shape

(960, 6)

In [0]:
np.random.seed(1000)

In [0]:
#Instantiate an empty model
model = Sequential()

# 1st Convolutional Layer
model.add(Conv2D(filters=96, input_shape=(227,227,3), kernel_size=(11,11), strides=(4,4), padding="valid"))
model.add(Activation("relu"))
# Max Pooling
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding="valid"))

# 2nd Convolutional Layer
model.add(Conv2D(filters=256, kernel_size=(11,11), strides=(1,1), padding="valid"))
model.add(Activation("relu"))
# Max Pooling
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding="valid"))

# 3rd Convolutional Layer
model.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding="valid"))
model.add(Activation("relu"))

# 4th Convolutional Layer
model.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding="valid"))
model.add(Activation("relu"))

# 5th Convolutional Layer
model.add(Conv2D(filters=256, kernel_size=(3,3), strides=(1,1), padding="valid"))
model.add(Activation("relu"))
# Max Pooling
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding="valid"))

# Passing it to a Fully Connected layer
model.add(Flatten())
# 1st Fully Connected Layer
model.add(Dense(4096, input_shape=(227*227*3,)))
model.add(Activation("relu"))
# Add Dropout to prevent overfitting
model.add(Dropout(0.4))

# 2nd Fully Connected Layer
model.add(Dense(4096))
model.add(Activation("relu"))
# Add Dropout
model.add(Dropout(0.4))

# 3rd Fully Connected Layer
model.add(Dense(1000))
model.add(Activation("relu"))
# Add Dropout
model.add(Dropout(0.4))

# Output Layer
model.add(Dense(6))
model.add(Activation('softmax'))

model.summary()

# Compile the model
model.compile(loss=keras.losses.categorical_crossentropy, optimizer='adam', metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_16 (Conv2D)           (None, 55, 55, 96)        34944     
_________________________________________________________________
activation_28 (Activation)   (None, 55, 55, 96)        0         
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 27, 27, 96)        0         
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 17, 17, 256)       2973952   
_________________________________________________________________
activation_29 (Activation)   (None, 17, 17, 256)       0         
_________________________________________________________________
max_pooling2d_11 (MaxPooling (None, 8, 8, 256)         0         
_________________________________________________________________
conv2d_18 (Conv2D)           (None, 6, 6, 384)         885120    
__________

In [0]:
model.fit(
    x = train_images,
    y = train_labels,
    batch_size = 32,
    epochs = 25,
    verbose = 1,
    validation_data = (dev_images, dev_labels)
)

Train on 960 samples, validate on 120 samples
Epoch 1/25
960/960 [==============================] - 158s 165ms/step - loss: 26.8337 - acc: 0.1740 - val_loss: 1.7925 - val_acc: 0.1667
Epoch 2/25
960/960 [==============================] - 156s 163ms/step - loss: 1.7909 - acc: 0.1604 - val_loss: 1.7657 - val_acc: 0.1583
Epoch 3/25
960/960 [==============================] - 156s 163ms/step - loss: 1.6989 - acc: 0.2365 - val_loss: 1.5936 - val_acc: 0.3833
Epoch 4/25
960/960 [==============================] - 155s 162ms/step - loss: 1.4296 - acc: 0.3802 - val_loss: 1.2628 - val_acc: 0.4583
Epoch 5/25
960/960 [==============================] - 156s 162ms/step - loss: 1.2110 - acc: 0.4802 - val_loss: 1.1557 - val_acc: 0.4750
Epoch 6/25
960/960 [==============================] - 156s 162ms/step - loss: 1.0377 - acc: 0.5854 - val_loss: 1.0545 - val_acc: 0.4667
Epoch 7/25
960/960 [==============================] - 155s 162ms/step - loss: 0.9505 - acc: 0.6156 - val_loss: 1.2110 - val_acc: 0.5417
E

In [0]:
model

In [0]:
# model.save('keras.h5')

In [0]:
from keras.models import load_model

In [0]:
loaded_model = load_model('keras.h5')

W0718 14:16:36.268393 140485173397376 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [0]:
test_images = []
test_real_labels = []
test_predicted_labels = []

In [0]:
ready_signs_test_root = "/content/drive/My Drive/DATA/READY_SIGNS/test_signs/"

counter = 0
for filename in os.listdir(ready_signs_test_root):
  index = int(filename[0])
#   label = np.zeros(6)
#   label[index] = 1
  
  image = Image.open(ready_signs_test_root + filename)
  image_array = np.array(image)
  image_array = image_array.flatten()
  test_images.append(image_array)
  test_real_labels.append(index)
  
  counter += 1
  if (counter % 50 == 0):
    print(counter)

50
100


In [0]:
test_images = np.stack(test_images, axis = 0)
test_real_labels = np.stack(test_real_labels, axis = 0)
test_images = scaler.transform(test_images)

In [0]:
test_images_list = []
for image in test_images:
  test_images_list.append(np.reshape(image, (227, 227, 3)))

In [0]:
test_images = np.array(test_images_list)
test_real_labels = np.array(test_real_labels)

In [0]:
predictions = loaded_model.predict(
    x = test_images,
    verbose = 1
)

120/120 [==============================] - 5s 38ms/step


In [0]:
predictions[0]

array([1.0000000e+00, 4.7320009e-11, 3.6694415e-11, 6.1059739e-14,
       9.2262937e-15, 4.3333922e-15], dtype=float32)

In [0]:
for prediction in predictions:
  label = np.argmax(prediction)
#   print(prediction, label)
  test_predicted_labels.append(label)

In [0]:
test_real_labels[0:20]

array([0, 5, 4, 0, 2, 3, 2, 1, 5, 5, 1, 3, 3, 4, 3, 5, 1, 4, 3, 1])

In [0]:
test_predicted_labels[0:20]

[0, 5, 4, 0, 2, 3, 0, 1, 5, 5, 1, 3, 3, 3, 5, 5, 1, 4, 3, 1]

In [0]:
from sklearn.metrics import multilabel_confusion_matrix

In [0]:
confusion_matrices = multilabel_confusion_matrix(test_real_labels, test_predicted_labels)

In [0]:
# TN - 0,0 FN - 1,0 TP - 1,1 FP - 0,1
for index in range(0,6):
  print("Confusion matrix for label " , index, " \n", confusion_matrices[index])

Confusion matrix for label  0  
 [[98  2]
 [ 1 19]]
Confusion matrix for label  1  
 [[98  2]
 [ 1 19]]
Confusion matrix for label  2  
 [[98  2]
 [ 6 14]]
Confusion matrix for label  3  
 [[96  4]
 [ 2 18]]
Confusion matrix for label  4  
 [[96  4]
 [ 8 12]]
Confusion matrix for label  5  
 [[93  7]
 [ 3 17]]


In [0]:
from sklearn.metrics import f1_score

In [0]:
type(list(test_real_labels))

list

In [0]:
# set(test_real_labels) - set(test_predicted_labels)

In [0]:
# test_predicted_labels

In [0]:
f1_score(list(test_real_labels), test_predicted_labels, average='weighted')

0.8213288518166567

In [0]:
train = StandardScaler()

In [0]:
x = np.load('mean.npy')

In [0]:
x

array([229.4875    , 221.48333333, 211.46145833, ..., 182.01145833,
       168.79791667, 158.32291667])

In [0]:
train.mean_ = x

In [0]:
train.mean_

array([229.4875    , 221.48333333, 211.46145833, ..., 182.01145833,
       168.79791667, 158.32291667])

In [0]:
scaler.scale_

array([ 4.02360871,  5.05384892,  6.45727738, ..., 38.23023555,
       47.61819501, 53.75904862])